// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu5lPcKzTt-FRO07nvo8n3pxxe4_ks3nU',
    appId: '1:26700290327:android:1c78abc1d1e44071b9ff52',
    messagingSenderId: '26700290327',
    projectId: 'spendo-mood',
    databaseURL: 'https://spendo-mood-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'spendo-mood.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu7SelpGx0nTtxR78S4V8wJCOGaWhIiPg',
    appId: '1:26700290327:ios:f57f833b89ec1c7ab9ff52',
    messagingSenderId: '26700290327',
    projectId: 'spendo-mood',
    databaseURL: 'https://spendo-mood-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'spendo-mood.firebasestorage.app',
    iosBundleId: 'com.example.emotiSpend',
  );
}
