// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_7ce-zGFOMDexCL9Ff5lDUADmd67pSUQ',
    appId: '1:216048233251:android:2a009b0eb41a021b047a96',
    messagingSenderId: '216048233251',
    projectId: 'emotispend',
    storageBucket: 'emotispend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA49Lkst7hzxveRFZGjmZ59Ae_5X1TyJ-s',
    appId: '1:216048233251:ios:a6ef7144304ebdd6047a96',
    messagingSenderId: '216048233251',
    projectId: 'emotispend',
    storageBucket: 'emotispend.firebasestorage.app',
    iosBundleId: 'com.example.emotiSpend',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf2ZIrFrrBzkv5_2yFZWaozKCxSNWvGJw',
    appId: '1:216048233251:web:751babccf7e30b60047a96',
    messagingSenderId: '216048233251',
    projectId: 'emotispend',
    authDomain: 'emotispend.firebaseapp.com',
    storageBucket: 'emotispend.firebasestorage.app',
    measurementId: 'G-VKGTR5EJRJ',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA49Lkst7hzxveRFZGjmZ59Ae_5X1TyJ-s',
    appId: '1:216048233251:ios:a6ef7144304ebdd6047a96',
    messagingSenderId: '216048233251',
    projectId: 'emotispend',
    storageBucket: 'emotispend.firebasestorage.app',
    iosBundleId: 'com.example.emotiSpend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBf2ZIrFrrBzkv5_2yFZWaozKCxSNWvGJw',
    appId: '1:216048233251:web:43728fec36424254047a96',
    messagingSenderId: '216048233251',
    projectId: 'emotispend',
    authDomain: 'emotispend.firebaseapp.com',
    storageBucket: 'emotispend.firebasestorage.app',
    measurementId: 'G-D72KZG9DFK',
  );

}